import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const documents = JSON.parse(await readFile(path.join(root, 'data/documents.json'), 'utf8')).documents;
const routes = JSON.parse(await readFile(path.join(root, 'data/source-routes.json'), 'utf8')).routes;
const sourcePages = JSON.parse(await readFile(path.join(root, 'evidence/source-content-2026-09-10/pages.json'), 'utf8')).pages;

const escapeHtml = value => String(value ?? '')
  .replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;').replaceAll("'", '&#039;');

const nav = [
  ['home', 'Home', 'index.html'],
  ['services', 'Services', 'services/'],
  ['parks', 'Parks & Places', 'parks/'],
  ['government', 'District & Board', 'government/'],
  ['history', 'Discover Brooktrails', 'history/'],
];

function prefixFor(rel) {
  const depth = rel.split('/').length - 1;
  return '../'.repeat(depth);
}

function icon(name) {
  const paths = {
    water: '<path d="M24 5S10 20 10 31a14 14 0 0 0 28 0C38 20 24 5 24 5Z"/><path d="M17 32c1 5 4 7 8 8"/>',
    tree: '<path d="m24 5-9 14h5L11 31h9v12h8V31h9l-9-12h5L24 5Z"/>',
    plan: '<path d="M7 39h34M10 36V15l14-8 14 8v21M17 36V25h14v11"/><path d="M7 18 24 8l17 10"/>',
    board: '<path d="M8 38h32M12 34V18h24v16M18 18v-6h12v6M17 25h2m5 0h2m5 0h2M17 31h2m5 0h2m5 0h2"/>',
    docs: '<path d="M12 5h17l7 7v31H12Z"/><path d="M29 5v8h7M18 22h12M18 28h12M18 34h8"/>',
    phone: '<path d="M14 7 8 10c2 15 15 28 30 30l3-6-9-5-4 4c-6-3-10-7-13-13l4-4-5-9Z"/>',
    compass: '<circle cx="24" cy="24" r="17"/><path d="m30 18-4 8-8 4 4-8 8-4Z"/><path d="M24 4v4m0 32v4M4 24h4m32 0h4"/>',
  };
  return `<svg class="icon" viewBox="0 0 48 48" aria-hidden="true">${paths[name] || paths.docs}</svg>`;
}

function header(active, p) {
  return `<a class="skip-link" href="#main-content">Skip to main content</a>
  <div class="safety-bar">
    <div class="shell safety-grid">
      <a class="safety-call" href="tel:911"><span>Emergency</span><strong>Call 911</strong></a>
      <a href="https://mendoready.org/" target="_blank" rel="noopener"><span>County updates</span><strong>Incidents & Evacuations ↗</strong></a>
      <a href="https://mendoready.org/plan-prepare/" target="_blank" rel="noopener"><span>Be ready</span><strong>Alerts & Evacuation Zones ↗</strong></a>
    </div>
  </div>
  <header class="site-header" data-header>
    <div class="shell masthead">
      <a class="brand" href="${p}index.html" aria-label="Brooktrails Township home">
        <span class="brand-mark" aria-hidden="true"><svg viewBox="0 0 64 64"><path d="M32 3 57 13v19c0 15-9 24-25 29C16 56 7 47 7 32V13L32 3Z"/><path d="m31 13-9 15h5l-8 13h10v10h6V41h10l-8-13h5L31 13Z"/></svg></span>
        <span><strong>Brooktrails Township</strong><small>Community Services District</small></span>
      </a>
      <div class="masthead-actions">
        <form class="site-search" role="search" data-site-search data-search-index="${p}search-index.json" data-search-root="${p}">
          <label class="sr-only" for="site-search-${active || 'utility'}">Search the Brooktrails site</label>
          <span aria-hidden="true">⌕</span><input id="site-search-${active || 'utility'}" type="search" placeholder="Search site" autocomplete="off" aria-autocomplete="list" aria-controls="site-search-results-${active || 'utility'}" aria-expanded="false" data-site-search-input>
          <div class="site-search-results" id="site-search-results-${active || 'utility'}" role="listbox" hidden data-site-search-results></div>
        </form>
        <a class="button button-small" href="${p}contact/">District desk</a>
      </div>
      <button class="menu-button" type="button" aria-expanded="false" aria-controls="site-nav" data-menu-button><span class="sr-only">Open navigation</span><i></i><i></i><i></i></button>
    </div>
    <nav class="site-nav" id="site-nav" aria-label="Primary navigation" data-nav>
      <div class="shell nav-list">${nav.map(([id, label, href]) => `<a ${id === active ? 'aria-current="page"' : ''} href="${p}${href}">${label}</a>`).join('')}</div>
    </nav>
  </header>`;
}

function footer(p) {
  return `<footer class="site-footer">
    <div class="shell footer-grid">
      <div><strong>Brooktrails Township CSD</strong><p>Essential public services for a forest community northwest of Willits, California.</p></div>
      <div><span class="footer-label">District office</span><p>24860 Birch Street<br>Willits, CA 95490<br><a href="tel:+17074592494">707-459-2494</a></p></div>
      <nav aria-label="Footer navigation"><a href="${p}government/">District & Board</a><a href="${p}resources/">Search records & forms</a><a href="${p}contact/">District Desk</a><a href="https://www.btcsd.org/" target="_blank" rel="noopener">Current district site ↗</a></nav>
    </div>
    <div class="shell footer-base"><span>© <span data-year>2026</span> Brooktrails Township</span><span>Public information, accessible by design.</span></div>
  </footer>`;
}

function page(rel, { title, description, active, route = active, eyebrow, heading, lede, heroImage, heroAlt, body, wide = false }) {
  const p = prefixFor(rel);
  const hero = `<section class="page-hero${heroImage ? ' page-hero-image' : ''}">
    <div class="shell ${heroImage ? 'page-hero-grid' : ''}">
      <div class="page-hero-copy"><p class="eyebrow">${eyebrow}</p><h1>${heading}</h1><p>${lede}</p></div>
${heroImage ? `<figure><img src="${p}${heroImage}" alt="${heroAlt}" width="768" height="576"></figure>` : ''}
    </div>
  </section>`;
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="theme-color" content="#06110f"><meta name="description" content="${escapeHtml(description)}"><title>${escapeHtml(title)} | Brooktrails Township</title><link rel="icon" href="${p}assets/favicon.svg"><link rel="stylesheet" href="${p}styles.css?v=20260930-2"><script src="${p}script.js?v=20260930-2" defer></script></head>
<body class="page-${route}"><div class="site-atmosphere" aria-hidden="true"></div>${header(active, p)}<main id="main-content">${hero}<div class="${wide ? '' : 'page-content'}">${body}</div></main>${footer(p)}</body></html>`;
}

async function write(rel, content) {
  const target = path.join(root, rel);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, content);
}

function findDoc(pattern) {
  const rx = new RegExp(pattern, 'i');
  return documents.find(d => rx.test(d.title));
}

function docHref(pattern, fallback = 'resources/') {
  const document = findDoc(pattern);
  return document ? document.file : fallback;
}

function docLink(pattern, label) {
  const d = findDoc(pattern);
  return d ? `<a class="resource-link" href="${prefixFor('x/index.html')}${d.file}">${label || escapeHtml(d.title)} <span aria-hidden="true">↓</span></a>` : '';
}

function sourceId(url) {
  const sourcePath = new URL(url).pathname.replace(/^\/+|\/+$/g, '') || 'home';
  return `source-${sourcePath.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`;
}

const resourceCategories = [
  { id: 'forms', label: 'Forms & applications', hint: 'Start or request something', pattern: /application|request|payment plan|shut-off|questionnaire|agreement|employment|rental|sewer lateral/i },
  { id: 'water', label: 'Water & sewer', hint: 'Quality, rates, service, conservation', pattern: /water|sewer|utility|consumer confidence|rate|fee|meter|wastewater|wet wipe/i },
  { id: 'parks', label: 'Parks & places', hint: 'Trails, greenbelt, rentals, recreation', pattern: /park|trail|greenbelt|recreation|committee|golf|stewardship|ohl/i },
  { id: 'board', label: 'Board & finance', hint: 'Meetings, budget, audit, operations', pattern: /agenda|minute|audit|financial|budget|compensation|organizational|municipal service|enterprise/i },
  { id: 'planning', label: 'Planning & property', hint: 'Design, building, standards, maps', pattern: /development|design review|specific plan|building|construction|road|tree|grading|chapter 20/i },
  { id: 'rules', label: 'Rules & policies', hint: 'Policies, ordinances, resolutions, code', pattern: /policy|ordinance|resolution|code/i },
  { id: 'history', label: 'History & maps', hint: 'Articles, brochures, archives, maps', pattern: /history|historical|1939|1967|map|article|brochure/i },
];

function categoriesFor(document) {
  const source = `${document.title} ${document.referencedFrom.join(' ')}`;
  const matches = resourceCategories.filter(category => category.pattern.test(source)).map(category => category.id);
  return matches.length ? matches : ['other'];
}

const fireOnlyDocumentTitles = /applications for volunteers|fire safety|wildfire preparedness/i;
const districtDocuments = documents.filter(document => !fireOnlyDocumentTitles.test(document.title));
const siteSearchIndex = [
  { title:'Services', detail:'Water, sewer, property, planning, records, and help', type:'Hub', href:'services/', keywords:'resident utility property forms contact' },
  { title:'Water & Sewer', detail:'Billing, water quality, conservation, rates, and laterals', type:'Service', href:'water/', keywords:'bill payment lake reservoir wastewater utility' },
  { title:'Planning & Development', detail:'Property review, applications, standards, and approvals', type:'Service', href:'planning/', keywords:'building grading tree cutting construction county' },
  { title:'Parks & Places', detail:'Trails, gatherings, greenbelt, golf, and stewardship', type:'Hub', href:'parks/', keywords:'redwood recreation rental ohl grove trailhead' },
  { title:'Ordinance 63', detail:'Retained source establishing Brooktrails Redwood Park', type:'Direct answer', href:'archive/#source-ordinance-63', keywords:'park rule conservation 1988 establishment' },
  { title:'District & Board', detail:'People, meetings, decisions, money, rules, and employment', type:'Hub', href:'government/', keywords:'government board public civic policy' },
  { title:'Next Board meeting', detail:'Open the meeting and agenda panel', type:'Direct answer', href:'government/#civic-panel-meeting', keywords:'agenda date participate public comment' },
  { title:'Employment', detail:'Current-opening guidance and retained application', type:'Direct answer', href:'government/#civic-panel-work', keywords:'job jobs work career application' },
  { title:'Discover Brooktrails', detail:'Origins, forest, water, maps, and photographs', type:'Hub', href:'history/', keywords:'history diamond ranch essence story' },
  { title:'Search records & forms', detail:`Search ${districtDocuments.length} retained district files`, type:'Tool', href:'resources/', keywords:'documents library pdf ordinances policies applications' },
  { title:'District Desk', detail:'Phone, email, address, fax, and golf contact', type:'Tool', href:'contact/', keywords:'contact office ask report issue phone email' },
  ...districtDocuments.map(document => ({
    title: document.title,
    detail: `${document.contentType.includes('pdf') ? 'PDF' : 'DOCX'} public record`,
    type: 'Document',
    href: document.file,
    keywords: document.referencedFrom.join(' '),
  })),
];
await write('search-index.json', JSON.stringify(siteSearchIndex));

const homeBody = `<section class="home-hero">
  <div class="shell home-hero-grid"><div class="home-hero-copy"><p class="eyebrow eyebrow-light">Your field guide to Brooktrails</p><h1>Between the Water<br><em>and the Redwoods,</em></h1><p>One forest community. Four clear ways in. Choose the part of Brooktrails that matters to you right now.</p><div class="button-row"><a class="button button-light" href="#hub-springboards">Choose your way in</a></div><div class="hero-signal" aria-label="Brooktrails overview"><span><b>4</b> distinct hubs</span><span><b>${districtDocuments.length}</b> searchable records</span><span><b>2,500</b> park acres</span></div></div><figure class="home-hero-image"><img src="assets/images/lake-emily.jpg" alt="Lake Emily surrounded by forest in Brooktrails" width="768" height="576"><figcaption>Lake Emily, part of the Brooktrails water supply</figcaption></figure></div>
  <nav class="shell utility-dock" aria-label="Common district tools"><a href="https://www.btcsd.org/" target="_blank" rel="noopener">Pay water bill <span>↗</span></a><a href="resources/">Search records & forms <span>→</span></a><a href="contact/">District Desk <span>→</span></a></nav>
</section>
<section class="section hub-section" id="hub-springboards"><div class="shell"><div class="section-intro"><div><p class="eyebrow">Four ways into Brooktrails</p><h2>Follow the cue that feels like yours.</h2></div><p>Each gateway owns a different kind of visit. The shapes change because the destinations do, and none of them drops you into a duplicate menu.</p></div>
  <nav class="hub-springboards" aria-label="Brooktrails information hubs">
    <a class="hub-springboard hub-current" href="services/"><span class="hub-current-ripple" aria-hidden="true"></span><span class="hub-copy"><small>Follow the current</small><strong>Services</strong><em>Water, sewer, property, planning, and help</em></span><span class="hub-go" aria-hidden="true">Flow in →</span></a>
    <a class="hub-springboard hub-trailhead" href="parks/"><span class="trail-post" aria-hidden="true"><i></i><b></b></span><span class="hub-copy"><small>Take the forest path</small><strong>Parks & Places</strong><em>Trails, gatherings, greenbelt, golf, and stewardship</em></span><span class="hub-go" aria-hidden="true">Set out →</span></a>
    <a class="hub-springboard hub-docket" href="government/"><span class="docket-tab" aria-hidden="true">PUBLIC</span><span class="hub-copy"><small>Open the public record</small><strong>District & Board</strong><em>People, meetings, decisions, money, rules, and work</em></span><span class="hub-go" aria-hidden="true">Open docket →</span></a>
    <a class="hub-springboard hub-compass" href="history/"><span class="compass-rose" aria-hidden="true"><i></i></span><span class="hub-copy"><small>Find what is beneath the canopy</small><strong>Discover Brooktrails</strong><em>Origins, water, maps, photographs, and the forest promise</em></span><span class="hub-go" aria-hidden="true">Choose a bearing →</span></a>
  </nav>
</div></section>
<section class="section landscape-band"><div class="shell landscape-grid"><div><p class="eyebrow eyebrow-light">The landscape is the infrastructure</p><h2>Everything starts with this place.</h2><p>Brooktrails sits northwest of Willits in northern Mendocino County. The district helps protect essential infrastructure, local recreation, and roughly 2,500 acres dedicated as conservation land in Brooktrails Redwood Park.</p></div><div class="stat-stack"><div><strong>2,500</strong><span>approximate acres dedicated to Redwood Park</span></div><div><strong>60</strong><span>miles of water mains described by the district</span></div><div><strong>${districtDocuments.length}</strong><span>district records in the guided library</span></div></div></div></section>
<section class="section"><div class="shell split-feature"><div><p class="eyebrow">Public service has faces</p><h2>Local decisions, without the fog.</h2><p>Brooktrails is managed by people who live with the consequences of local decisions. The District & Board hub keeps meetings, responsibility, and public records together.</p></div><figure class="board-group-photo"><img src="assets/images/board-of-directors-2025.jpg" alt="Brooktrails Township Board of Directors pictured in 2025" width="1170" height="724"><figcaption><strong>Left to right:</strong> Susan Mahoney, Mary Ziady, Tina Tyler-O'Shea, Ed Horrick, and Rick Williams. Source image dated 2025.</figcaption></figure></div></section>`;

await write('index.html', `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="theme-color" content="#06110f"><meta name="description" content="Brooktrails Township Community Services District information for water, sewer, parks, planning, meetings, and public documents."><title>Brooktrails Township Community Services District</title><link rel="icon" href="assets/favicon.svg"><link rel="stylesheet" href="styles.css?v=20260930-2"><script src="script.js?v=20260930-2" defer></script></head><body class="page-home"><div class="site-atmosphere" aria-hidden="true"></div>${header('home','')}<main id="main-content">${homeBody}</main>${footer('')}</body></html>`);

const servicesBody = `<section class="section section-tint"><div class="shell"><div class="section-intro"><div><p class="eyebrow">Start with what you need</p><h2>Four outcomes. One service switchboard.</h2></div><p>Choose the outcome, not the department name. Each line goes directly to the explanation, records, or person needed to move forward.</p></div><nav class="service-switchboard" aria-label="Resident service pathways">
  <a href="../water/"><span>${icon('water')}</span><strong>Handle water & sewer</strong><small>Billing, quality, conservation, rates, shut-off policy, and laterals</small><b>Open utility desk →</b></a>
  <a href="../planning/"><span>${icon('plan')}</span><strong>Plan work on a property</strong><small>Development review, standards, applications, and county coordination</small><b>Map the approval path →</b></a>
  <a href="../resources/"><span>${icon('docs')}</span><strong>Find a form or record</strong><small>Search the retained public library by task, category, or title</small><b>Search records →</b></a>
  <a href="../contact/"><span>${icon('phone')}</span><strong>Ask the district</strong><small>Confirm timing, fees, availability, or a changing process with staff</small><b>Open District Desk →</b></a>
</nav></div></section>
<section class="section"><div class="shell two-column"><div><p class="eyebrow">A simpler information architecture</p><h2>Services are organized around resident intent.</h2><p>Water and sewer remain together. Planning and property review remain together. Forms and public records can be searched independently. Board business has its own civic desk.</p><a class="text-link" href="../government/">Looking for Board business? Enter the civic desk →</a></div><aside class="callout callout-green"><h3>Not sure where to start?</h3><p>Call the district office at 707-459-2494. Staff can confirm the current process before you depend on a captured form or policy.</p><a class="button button-light" href="tel:+17074592494">Call the district</a></aside></div></section>`;
await write('services/index.html',page('services/index.html',{title:'Services',description:'A simplified starting point for Brooktrails water, sewer, planning, property, forms, records, and district contacts.',active:'services',eyebrow:'Services',heading:'Start with what you came to do.',lede:'Water, property, records, and help are organized around real resident tasks instead of departmental labels.',body:servicesBody}));

const waterBody = `<nav class="water-jump" aria-label="On this water and sewer page"><div class="shell"><a href="#billing">Billing & documents</a><a href="#system">The water system</a><a href="#conservation">Conservation</a><a href="#sewer">Sewer & laterals</a></div></nav>
<section class="section" id="system"><div class="shell"><div class="metric-row"><div><strong>9,000</strong><span>gallon monthly customer use limit</span></div><div><strong>1.2 MGD</strong><span>water treatment design capacity</span></div><div><strong>60 miles</strong><span>of water mains</span></div><div><strong>18</strong><span>pump stations</span></div></div></div></section>
<section class="section section-tint" id="billing"><div class="shell"><div class="section-intro"><div><p class="eyebrow">Resident utility desk</p><h2>Common water & sewer needs</h2></div><p>Use the district's published resources, or call the office before relying on connection availability or a time-sensitive policy.</p></div><div class="action-grid"><a href="https://www.btcsd.org/" target="_blank" rel="noopener"><strong>Pay your bill</strong><span>Open current district payment access ↗</span></a>${['Consumer Confidence','Rates and Fees','Utilities Code','Payment Plan','Water Shut-Off','sewer lateral'].map((q,i)=>{const d=findDoc(q);return d?`<a href="../${d.file}"><strong>${escapeHtml(d.title)}</strong><span>Download ${d.contentType.includes('pdf')?'PDF':'file'} ↓</span></a>`:''}).join('')}</div></div></section>
<section class="section"><div class="shell story-grid"><div><p class="eyebrow">Brooktrails water system</p><h2>Surface water, stored close to home.</h2><p>The district describes two reservoirs totaling about 400 acre-feet on Willits Creek and a tributary. Lake Emily feeds Lake Ada Rose before water moves to the treatment plant.</p><p>The public system description includes a 1.2 million gallon-per-day treatment plant, 60 miles of mains, 24 water tanks, and 18 pump stations. Annual Consumer Confidence Reports provide testing and water-quality results.</p><a class="text-link" href="../${docHref('Consumer Confidence')}">Read the 2025 Consumer Confidence Report →</a></div><div class="image-pair"><figure><img src="../assets/images/lake-emily.jpg" alt="Lake Emily reservoir"><figcaption>Lake Emily</figcaption></figure><figure><img src="../assets/images/lake-ada-rose.jpg" alt="Lake Ada Rose reservoir"><figcaption>Lake Ada Rose</figcaption></figure></div></div></section>
<section class="section forest-panel" id="conservation"><div class="shell two-column"><div><p class="eyebrow eyebrow-light">Conservation</p><h2>Save water when the power goes out.</h2><p>The system relies on electric pumps to fill storage tanks. During outages, using less water helps the community maintain service while generators support the system.</p><p>Every water customer is subject to a 9,000 gallon monthly use limit. The district's conservation resources cover meter reading, indoor and outdoor efficiency, rainwater, graywater, pools, irrigation, and professional resources.</p></div><aside class="callout"><h3>Water service and new connections</h3><p>Published source pages contain different point-in-time connection counts. Availability changes. Contact the district office before planning a purchase or construction project.</p><a class="button button-light" href="../contact/">Contact utilities</a></aside></div></section>
<section class="section" id="sewer"><div class="shell two-column"><div><p class="eyebrow">Wastewater</p><h2>Sewer service & lateral inspections</h2><p>The district provides wastewater collection for most of Brooktrails, while Spring Creek, Sylvandale, and some higher-elevation Brooktrails properties are not served by the collection system. Wastewater is treated at the City of Willits Wastewater Treatment Plant.</p><p>Sewer lateral inspections are required when an owner or tenant moves into a residence that has not been inspected within the last five years. Check with the district office for the address's last inspection date.</p></div><div class="resource-panel"><h3>Utility documents</h3>${['sewer lateral','Ordinance 121','no wet wipe','water meter construction','Rates and Fees'].map(q=>{const d=findDoc(q);return d?`<a href="../${d.file}">${escapeHtml(d.title)} <span>↓</span></a>`:''}).join('')}</div></div></section>`;
await write('water/index.html', page('water/index.html',{title:'Water & Sewer',description:'Brooktrails water, sewer, billing, conservation, water quality, and utility forms.',active:'services',route:'water',eyebrow:'Water & sewer',heading:'Reliable service starts with clear information.',lede:'Pay a bill, understand the water system, conserve supplies, and find the forms and reports that support your property.',heroImage:'assets/images/lake-emily.jpg',heroAlt:'Lake Emily, a Brooktrails water source',body:waterBody}));

await write('fire/index.html', `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta http-equiv="refresh" content="0;url=../archive/"><title>Fire information moved | Brooktrails Township</title><link rel="canonical" href="../archive/"><link rel="stylesheet" href="../styles.css?v=20260930-2"></head><body class="page-redirect"><main class="redirect-page"><h1>Fire information is moving to a separate website.</h1><p>The district source material remains available in the retained archive.</p><p><a class="button" href="../archive/">Open retained source archive</a></p></main></body></html>`);

const parksBody = `<section class="section section-tint"><div class="shell"><div class="section-intro"><div><p class="eyebrow">Choose your way outside</p><h2>What sounds good today?</h2></div><p>Pick an experience. The field card opens the maps, forms, rules, and next steps that belong together.</p></div>
<div class="story-deck story-deck-parks" data-story-deck>
  <div class="story-deck-rail" role="tablist" aria-label="Parks and recreation activities">
    <button class="story-deck-tab is-active" id="parks-tab-trails" type="button" role="tab" aria-selected="true" aria-controls="parks-panel-trails" tabindex="0" data-story-target="parks-panel-trails"><span>01</span><strong>Find a trail</strong><small>Maps, trailheads, redwoods</small></button>
    <button class="story-deck-tab" id="parks-tab-gather" type="button" role="tab" aria-selected="false" aria-controls="parks-panel-gather" tabindex="-1" data-story-target="parks-panel-gather"><span>02</span><strong>Gather under the trees</strong><small>Community Center, Ohl Grove</small></button>
    <button class="story-deck-tab" id="parks-tab-care" type="button" role="tab" aria-selected="false" aria-controls="parks-panel-care" tabindex="-1" data-story-target="parks-panel-care"><span>03</span><strong>Care for the greenbelt</strong><small>Report, volunteer, participate</small></button>
    <button class="story-deck-tab" id="parks-tab-story" type="button" role="tab" aria-selected="false" aria-controls="parks-panel-story" tabindex="-1" data-story-target="parks-panel-story"><span>04</span><strong>Understand the park promise</strong><small>Stewardship, plans, rules</small></button>
    <button class="story-deck-tab" id="parks-tab-golf" type="button" role="tab" aria-selected="false" aria-controls="parks-panel-golf" tabindex="-1" data-story-target="parks-panel-golf"><span>05</span><strong>Tee off among the trees</strong><small>Golf information and contact</small></button>
  </div>
  <div class="story-deck-stage" aria-live="polite">
    <article class="story-deck-panel is-active" id="parks-panel-trails" role="tabpanel" aria-labelledby="parks-tab-trails" data-story-panel>
      <p class="story-deck-kicker">Trail file 01 · Explore</p><h3>Put the redwoods within walking distance.</h3><p>Brooktrails Redwood Park connects active-use, neighborhood-use, and passive-use areas across land set aside for conservation and recreation.</p><ol><li><strong>Choose a route.</strong> Start with the retained hiking trail map.</li><li><strong>Locate the trailhead.</strong> Open live map directions before leaving.</li><li><strong>Tread lightly.</strong> Pack out what you bring and report trail issues.</li></ol><div class="button-row"><a class="button" href="../${docHref('Hiking Trail Map')}">Open trail map</a><a class="button button-outline-dark" href="https://www.google.com/maps/search/?api=1&query=Brooktrails+Redwood+Park+Willits+CA" target="_blank" rel="noopener">Find a trailhead ↗</a></div>
    </article>
    <article class="story-deck-panel" id="parks-panel-gather" role="tabpanel" aria-labelledby="parks-tab-gather" data-story-panel hidden>
      <p class="story-deck-kicker">Field file 02 · Gather</p><h3>Make the forest your gathering room.</h3><p>Two retained applications help residents begin planning a community gathering. Availability, fees, and approval remain subject to district confirmation.</p><ol><li><strong>Choose the setting.</strong> Compare the Community Center and Ohl Redwood Grove.</li><li><strong>Review the application.</strong> Check rules, capacity, and requested dates.</li><li><strong>Confirm with staff.</strong> Contact the district before making dependent plans.</li></ol><div class="story-deck-links"><a href="../${docHref('Community Center Rental')}">Community Center application <span>↓</span></a><a href="../${docHref('Ohl Redwood Grove')}">Ohl Redwood Grove application <span>↓</span></a></div>
    </article>
    <article class="story-deck-panel" id="parks-panel-care" role="tabpanel" aria-labelledby="parks-tab-care" data-story-panel hidden>
      <p class="story-deck-kicker">Field file 03 · Steward</p><h3>Leave the greenbelt better than you found it.</h3><p>The Recreation, Greenbelt & Conservation Committee supports public participation, and Willits Area Cyclists partners with the district on organized trail stewardship.</p><ol><li><strong>Spot a problem.</strong> Note the trail, nearest landmark, and condition.</li><li><strong>Send a useful report.</strong> Tell the District Desk which trail and landmark you observed.</li><li><strong>Join the conversation.</strong> Confirm the committee's next meeting with the district.</li></ol><div class="story-deck-links"><a href="../contact/?topic=trails">Ask about trail maintenance <span>→</span></a><a href="../${docHref('Committee Charter')}">Committee charter <span>↓</span></a></div>
    </article>
    <article class="story-deck-panel" id="parks-panel-story" role="tabpanel" aria-labelledby="parks-tab-story" data-story-panel hidden>
      <p class="story-deck-kicker">Field file 04 · Preserve</p><h3>A park built from a conservation promise.</h3><p>Approximately 2,500 acres were dedicated for conservation and recreation. Ordinance 63 formally established Brooktrails Redwood Park in 1988, followed by a master plan and later stewardship work.</p><ol><li><strong>See the boundary.</strong> Open the park map and trail system.</li><li><strong>Read the rule.</strong> Ordinance 63 records the park's establishment.</li><li><strong>Follow the long view.</strong> The stewardship plan guides care for the greenbelt.</li></ol><div class="story-deck-links"><a href="../archive/#source-ordinance-63">Read retained Ordinance 63 <span>→</span></a><a href="../${docHref('Greenbelt Stewardship')}">Greenbelt stewardship plan <span>↓</span></a></div>
    </article>
    <article class="story-deck-panel" id="parks-panel-golf" role="tabpanel" aria-labelledby="parks-tab-golf" data-story-panel hidden>
      <p class="story-deck-kicker">Field file 05 · Play</p><h3>Send one down the fairway.</h3><p>Watch the shot, then call the course for current tee times, operating details, and conditions.</p><div class="golf-reveal" data-golf-reveal><div class="golf-landscape" aria-hidden="true"><span class="golf-sun"></span><span class="golf-redwoods golf-redwoods-back"></span><span class="golf-redwoods golf-redwoods-front"></span><span class="golf-fairway"></span><span class="golf-flag"></span></div><svg class="golf-player" viewBox="0 0 150 180" role="img" aria-label="Golfer teeing off"><circle cx="59" cy="31" r="13"/><path d="M55 45c-13 19-15 45-8 68l22 2c8-28 5-51-2-68Z"/><path d="m49 67-25 27m42-28 27 16M52 112l-18 48m31-46 22 45"/><g class="golf-club"><path d="M27 89 105 28"/><path d="m103 27 13-7"/></g></svg><span class="golf-ball" aria-hidden="true"></span><span class="golf-flight" aria-hidden="true"></span><a class="golf-phone" href="tel:+17074596761"><small>Tee times and course information</small><strong>707-459-6761</strong><span>Tap to call →</span></a></div><div class="button-row"><a class="button" href="https://www.btcsd.org/brooktrails-golf-course" target="_blank" rel="noopener">Explore the golf course ↗</a><button class="button button-outline-dark" type="button" data-golf-replay>Replay the shot</button></div>
    </article>
  </div>
</div></div></section>
<section class="section"><div class="shell story-grid"><div><p class="eyebrow">Brooktrails Redwood Park</p><h2>Conservation land woven through the community.</h2><p>The park's approximately 2,500 acres carry a long-running promise: make room for recreation while protecting the forest landscape that defines Brooktrails.</p><p>The complete source history, maps, ordinance, master-plan record, and stewardship materials remain available for people who want to go deeper.</p><a class="text-link" href="../history/">Discover how the promise began →</a></div><figure class="feature-photo"><img src="../assets/images/redwood-park-history.jpg" alt="Historical newspaper coverage of Brooktrails conservation plans"><figcaption>Historical coverage of the Brooktrails conservation vision</figcaption></figure></div></section>`;
await write('parks/index.html',page('parks/index.html',{title:'Parks & Places',description:'Brooktrails Redwood Park, conservation lands, trails, maps, rentals, and stewardship resources.',active:'parks',eyebrow:'Parks & places',heading:'Keep close to the redwoods.',lede:'Explore the conservation legacy, public-use areas, trails, rental resources, and community stewardship of Brooktrails Redwood Park.',heroImage:'assets/images/diamond-d-ranch-history.jpg',heroAlt:'Historic Diamond D Ranch headquarters in Brooktrails',body:parksBody}));

const planningBody = `<section class="section"><div class="shell"><div class="process"><div><span>1</span><h3>Start with the district</h3><p>Before grading, tree cutting, or construction, contact Township staff and review the Brooktrails standards.</p></div><div><span>2</span><h3>Prepare your plan</h3><p>Use the development standards, application packet, and construction water-meter materials.</p></div><div><span>3</span><h3>Coordinate county review</h3><p>Projects also require the applicable Mendocino County Planning & Building Services approval.</p></div></div></div></section>
<section class="section section-tint"><div class="shell two-column"><div><p class="eyebrow">Development review</p><h2>Plan first, then build.</h2><p>Brooktrails properties are subject to development standards and a review process consistent with the Brooktrails Specific Plan adopted by Mendocino County. Township staff, and the District Architect when required, evaluate proposed plans.</p><p>The district and county jointly administer the Brooktrails Specific Plan and its 2004 amendments.</p><a class="button" href="../contact/">Contact the Township office</a></div><div class="resource-panel"><h3>Planning packet</h3>${['Development Standards','Design Review Application','Water Meter Construction','Chapter 20.232','Ordinance 121','Ordinance 112','2004 Specific Plan'].map(q=>{const d=findDoc(q);return d?`<a href="../${d.file}">${escapeHtml(d.title)} <span>↓</span></a>`:''}).join('')}</div></div></section>
<section class="section"><div class="shell story-grid"><div><p class="eyebrow">Long-range planning</p><h2>Growth, water & a second access road.</h2><p>The district describes its planning authority as a response to water-right and growth questions raised in the late 1980s. A second access road has remained an important planning element, with alternative-route work presented in 2009 and funding limitations reported in 2013.</p><p>Historical planning records remain available in the document center so current decisions can be read in context.</p><a class="text-link" href="../resources/">Browse planning records →</a></div><figure class="feature-photo map-photo"><img src="../assets/images/water-system-map.jpg" alt="Map showing Brooktrails water system and tank locations"><figcaption>Water system and tank locations</figcaption></figure></div></section>`;
await write('planning/index.html',page('planning/index.html',{title:'Planning & Development',description:'Brooktrails planning, building and development review process, standards, applications, and historical planning context.',active:'services',route:'planning',eyebrow:'Planning & development',heading:'A clearer path from idea to approval.',lede:'Understand the Township and County review steps, gather the right documents, and contact staff before site work begins.',body:planningBody}));

const governmentBody = `<section class="section section-tint"><div class="shell"><div class="section-intro"><div><p class="eyebrow">The civic desk</p><h2>What do you want to know?</h2></div><p>One Board link is not a public-information strategy. Choose a question and the relevant people, meeting material, and records appear together.</p></div>
<div class="story-deck story-deck-civic" data-story-deck>
  <div class="story-deck-rail" role="tablist" aria-label="Board and district information">
    <button class="story-deck-tab is-active" id="civic-tab-board" type="button" role="tab" aria-selected="true" aria-controls="civic-panel-board" tabindex="0" data-story-target="civic-panel-board"><span>01</span><strong>Who represents me?</strong><small>Meet the Board</small></button>
    <button class="story-deck-tab" id="civic-tab-meeting" type="button" role="tab" aria-selected="false" aria-controls="civic-panel-meeting" tabindex="-1" data-story-target="civic-panel-meeting"><span>02</span><strong>What is happening next?</strong><small>Meetings and agenda</small></button>
    <button class="story-deck-tab" id="civic-tab-record" type="button" role="tab" aria-selected="false" aria-controls="civic-panel-record" tabindex="-1" data-story-target="civic-panel-record"><span>03</span><strong>What did the Board decide?</strong><small>Agendas and minutes</small></button>
    <button class="story-deck-tab" id="civic-tab-money" type="button" role="tab" aria-selected="false" aria-controls="civic-panel-money" tabindex="-1" data-story-target="civic-panel-money"><span>04</span><strong>Where does the money go?</strong><small>Budget, rates, audit</small></button>
    <button class="story-deck-tab" id="civic-tab-rules" type="button" role="tab" aria-selected="false" aria-controls="civic-panel-rules" tabindex="-1" data-story-target="civic-panel-rules"><span>05</span><strong>What rules guide the district?</strong><small>Policies and ordinances</small></button>
    <button class="story-deck-tab" id="civic-tab-inside" type="button" role="tab" aria-selected="false" aria-controls="civic-panel-inside" tabindex="-1" data-story-target="civic-panel-inside"><span>06</span><strong>Who runs daily operations?</strong><small>Administration and systems</small></button>
    <button class="story-deck-tab" id="civic-tab-work" type="button" role="tab" aria-selected="false" aria-controls="civic-panel-work" tabindex="-1" data-story-target="civic-panel-work"><span>07</span><strong>How can I work here?</strong><small>Employment and application</small></button>
  </div>
  <div class="story-deck-stage" aria-live="polite">
    <article class="story-deck-panel is-active" id="civic-panel-board" role="tabpanel" aria-labelledby="civic-tab-board" data-story-panel><p class="story-deck-kicker">Civic file 01 · Representation</p><h3>Five residents. One public trust.</h3><p>The Board sets district policy and appoints the General Manager, General Counsel, and Auditor. Hover a name on desktop or tap it on mobile to meet each member.</p><ol class="board-member-list"><li class="board-member"><button class="board-member-trigger" type="button" aria-expanded="false" aria-controls="portrait-tina" data-member-portrait-trigger><strong>Tina Tyler-O'Shea</strong><span>President</span></button><span class="board-member-portrait" id="portrait-tina" aria-hidden="true" data-member-portrait><img src="../assets/images/board/tina-tyler-oshea.webp" alt=""><b>Tina Tyler-O'Shea</b></span></li><li class="board-member"><button class="board-member-trigger" type="button" aria-expanded="false" aria-controls="portrait-rick" data-member-portrait-trigger><strong>Rick Williams</strong><span>Vice-President</span></button><span class="board-member-portrait" id="portrait-rick" aria-hidden="true" data-member-portrait><img src="../assets/images/board/rick-williams.webp" alt=""><b>Rick Williams</b></span></li><li class="board-member"><button class="board-member-trigger" type="button" aria-expanded="false" aria-controls="portrait-ed" data-member-portrait-trigger><strong>Ed Horrick</strong><span>Director</span></button><span class="board-member-portrait" id="portrait-ed" aria-hidden="true" data-member-portrait><img src="../assets/images/board/ed-horrick.webp" alt=""><b>Ed Horrick</b></span></li><li class="board-member"><button class="board-member-trigger" type="button" aria-expanded="false" aria-controls="portrait-susan" data-member-portrait-trigger><strong>Susan Mahoney</strong><span>Director</span></button><span class="board-member-portrait" id="portrait-susan" aria-hidden="true" data-member-portrait><img src="../assets/images/board/susan-mahoney.webp" alt=""><b>Susan Mahoney</b></span></li><li class="board-member"><button class="board-member-trigger" type="button" aria-expanded="false" aria-controls="portrait-mary" data-member-portrait-trigger><strong>Mary Ziady</strong><span>Director</span></button><span class="board-member-portrait" id="portrait-mary" aria-hidden="true" data-member-portrait><img src="../assets/images/board/mary-ziady.webp" alt=""><b>Mary Ziady</b></span></li></ol><p class="story-deck-note">Source image and membership are dated 2025. Confirm current membership with the district.</p></article>
    <article class="story-deck-panel" id="civic-panel-meeting" role="tabpanel" aria-labelledby="civic-tab-meeting" data-story-panel hidden><p class="story-deck-kicker">Civic file 02 · Participate</p><h3>Know what is on the table before the meeting starts.</h3><p>The latest posted agenda is the best starting point for date, time, location, and current business.</p><ol><li><strong>Open the latest agenda.</strong> Check the posted meeting details.</li><li><strong>Review the items.</strong> Note where public comment applies.</li><li><strong>Confirm if time-sensitive.</strong> Contact the office before relying on a captured file.</li></ol><div class="button-row"><a class="button" href="../${docHref('Agenda for Most Recent')}">Open latest agenda</a><a class="button button-outline-dark" href="../contact/">Contact the district</a></div></article>
    <article class="story-deck-panel" id="civic-panel-record" role="tabpanel" aria-labelledby="civic-tab-record" data-story-panel hidden><p class="story-deck-kicker">Civic file 03 · Follow through</p><h3>Trace an issue from agenda to record.</h3><p>Agendas show what was scheduled. Minutes and related records show what happened. The guided library keeps the captured meeting materials searchable.</p><ol><li><strong>Start with the subject.</strong> Search a project, policy, or service.</li><li><strong>Compare agenda and minutes.</strong> Read the public record in sequence.</li><li><strong>Ask for the current record.</strong> Contact staff when the captured set is not enough.</li></ol><a class="button" href="../resources/?category=board">Search Board records</a></article>
    <article class="story-deck-panel" id="civic-panel-money" role="tabpanel" aria-labelledby="civic-tab-money" data-story-panel hidden><p class="story-deck-kicker">Civic file 04 · Public money</p><h3>Follow the plan, the rates, and the audit.</h3><p>These records answer different questions: the financial plan sets direction, rates and fees affect service charges, and the annual audit reviews the completed fiscal year.</p><ol><li><strong>Plan.</strong> Read the financial plan for services.</li><li><strong>Price.</strong> Review the adopted rates and fees.</li><li><strong>Verify.</strong> Read the annual audit.</li></ol><div class="story-deck-links">${['Financial Plan','Rates and Fees','annual audit'].map(q=>{const d=findDoc(q);return d?`<a href="../${d.file}">${escapeHtml(d.title)} <span>↓</span></a>`:''}).join('')}</div></article>
    <article class="story-deck-panel" id="civic-panel-rules" role="tabpanel" aria-labelledby="civic-tab-rules" data-story-panel hidden><p class="story-deck-kicker">Civic file 05 · Rules</p><h3>Policy should be readable, not buried.</h3><p>The policy manual guides Board and administrative practice. Ordinances, resolutions, and utility rules establish more specific requirements.</p><ol><li><strong>Begin with the policy manual.</strong> Find the governing topic.</li><li><strong>Check the controlling record.</strong> Review relevant ordinances or resolutions.</li><li><strong>Confirm interpretation.</strong> Ask the district before acting on a legal or time-sensitive question.</li></ol><div class="button-row"><a class="button" href="../${docHref('Township Policy Manual')}">Open policy manual</a><a class="button button-outline-dark" href="../resources/?category=rules">Browse rules</a></div></article>
    <article class="story-deck-panel" id="civic-panel-inside" role="tabpanel" aria-labelledby="civic-tab-inside" data-story-panel hidden><p class="story-deck-kicker">Civic file 06 · Operations</p><h3>See who turns policy into service.</h3><p>The captured public source names Tamara Alaniz as General Manager, Christopher J. Neary as General Counsel, and JJACPA as Auditor. The General Manager directs daily Township operations under Board policy.</p><nav class="story-deck-destinations" aria-label="Administration, professional oversight, and public systems"><a class="story-deck-destination" href="../contact/"><span class="story-deck-destination-number">01</span><span class="story-deck-destination-copy"><strong>Administration</strong><small>Day-to-day district operations and staff contact.</small><b>Reach the district office</b></span><i aria-hidden="true">→</i></a><a class="story-deck-destination" href="../${docHref('annual audit')}"><span class="story-deck-destination-number">02</span><span class="story-deck-destination-copy"><strong>Professional oversight</strong><small>Counsel and independent audit roles.</small><b>Open the current audit</b></span><i aria-hidden="true">↓</i></a><a class="story-deck-destination" href="../${docHref('Enterprise Systems')}"><span class="story-deck-destination-number">03</span><span class="story-deck-destination-copy"><strong>Public systems</strong><small>The SB 272 catalog describes systems holding public information.</small><b>Open the systems catalog</b></span><i aria-hidden="true">↓</i></a></nav></article>
    <article class="story-deck-panel" id="civic-panel-work" role="tabpanel" aria-labelledby="civic-tab-work" data-story-panel hidden><p class="story-deck-kicker">Civic file 07 · Employment</p><h3>Put your work to use for the community.</h3><p>Employment status, qualifications, and deadlines can change. Use the retained application as a starting point and confirm current openings with the District Desk before applying.</p><ol><li><strong>Check current openings.</strong> Ask the district what is actively recruiting.</li><li><strong>Review the application.</strong> Gather the requested employment information.</li><li><strong>Confirm delivery.</strong> Verify the current deadline and submission method.</li></ol><div class="button-row"><a class="button" href="../${docHref('EMPLOYMENT APPLICATION')}">Open employment application</a><a class="button button-outline-dark" href="../contact/">Ask the District Desk</a></div></article>
  </div>
</div></div></section>
<section class="section"><div class="shell split-feature"><div><p class="eyebrow">Board of Directors</p><h2>Public service has faces.</h2><p>The Board image is retained as a dated source record, while the civic desk above organizes the questions residents most often bring to district government.</p><p>Terms and roles can change. Confirm current membership and meeting materials with the district office.</p><a class="text-link" href="../contact/">Reach the district office →</a></div><figure class="board-group-photo"><img src="../assets/images/board-of-directors-2025.jpg" alt="Five members of the Brooktrails Township Board of Directors" width="1170" height="724"><figcaption><strong>Left to right:</strong> Susan Mahoney, Mary Ziady, Tina Tyler-O'Shea, Ed Horrick, and Rick Williams. Source image dated 2025.</figcaption></figure></div></section>
`;
await write('government/index.html',page('government/index.html',{title:'District & Board',description:'Brooktrails Board, administration, meetings, public records, financials, policies, and employment information.',active:'government',eyebrow:'District & Board',heading:'Local decisions, made visible.',lede:'Meet the Board, follow district business, and reach the budgets, policies, audits, records, and employment information behind public service.',body:governmentBody}));

const historyBody = `<section class="section section-tint"><div class="shell"><div class="section-intro"><div><p class="eyebrow">Pick a thread</p><h2>There is more beneath the canopy.</h2></div><p>“More” should lead somewhere worth going. Choose the part of Brooktrails you want to understand and follow the story through the landscape.</p></div>
<div class="story-deck story-deck-discover" data-story-deck>
  <div class="story-deck-rail" role="tablist" aria-label="Discover Brooktrails stories">
    <button class="story-deck-tab is-active" id="discover-tab-origin" type="button" role="tab" aria-selected="true" aria-controls="discover-panel-origin" tabindex="0" data-story-target="discover-panel-origin"><span>01</span><strong>How did Brooktrails begin?</strong><small>Diamond D Ranch to community</small></button>
    <button class="story-deck-tab" id="discover-tab-forest" type="button" role="tab" aria-selected="false" aria-controls="discover-panel-forest" tabindex="-1" data-story-target="discover-panel-forest"><span>02</span><strong>Why protect 2,500 acres?</strong><small>The conservation promise</small></button>
    <button class="story-deck-tab" id="discover-tab-water" type="button" role="tab" aria-selected="false" aria-controls="discover-panel-water" tabindex="-1" data-story-target="discover-panel-water"><span>03</span><strong>Where does the water come from?</strong><small>Lake Emily to the tap</small></button>
    <button class="story-deck-tab" id="discover-tab-photos" type="button" role="tab" aria-selected="false" aria-controls="discover-panel-photos" tabindex="-1" data-story-target="discover-panel-photos"><span>04</span><strong>What did it look like then?</strong><small>Photos, articles, brochure</small></button>
    <button class="story-deck-tab" id="discover-tab-map" type="button" role="tab" aria-selected="false" aria-controls="discover-panel-map" tabindex="-1" data-story-target="discover-panel-map"><span>05</span><strong>How does the place fit together?</strong><small>Community and park maps</small></button>
  </div>
  <div class="story-deck-stage" aria-live="polite">
    <article class="story-deck-panel is-active" id="discover-panel-origin" role="tabpanel" aria-labelledby="discover-tab-origin" data-story-panel><p class="story-deck-kicker">Story 01 · Origins</p><h3>From working ranch to forest community.</h3><p>Brooktrails grew from the former Diamond D Ranch northwest of Willits. In the late 1960s, plans paired homes and infrastructure with a large conservation dedication.</p><ol><li><strong>Ranch landscape.</strong> The Diamond D Ranch anchors the early story.</li><li><strong>Planned community.</strong> Development brought roads, homes, and utility questions.</li><li><strong>Local district.</strong> Public services evolved through improvement districts into a Community Services District.</li></ol><a class="button" href="../archive/#source-the-essence-of-brooktrails">Read the retained source story</a></article>
    <article class="story-deck-panel" id="discover-panel-forest" role="tabpanel" aria-labelledby="discover-tab-forest" data-story-panel hidden><p class="story-deck-kicker">Story 02 · The promise</p><h3>Development made room for a living forest.</h3><p>Approximately 2,500 acres were dedicated for conservation and recreation, becoming the foundation of Brooktrails Redwood Park.</p><ol><li><strong>Dedication.</strong> Conservation land was woven into the original community plan.</li><li><strong>Establishment.</strong> Ordinance 63 formally created the park in 1988.</li><li><strong>Stewardship.</strong> Later plans shaped long-term greenbelt care.</li></ol><div class="button-row"><a class="button" href="../parks/">Explore the park</a><a class="button button-outline-dark" href="../${docHref('Greenbelt Stewardship')}">Read the plan</a></div></article>
    <article class="story-deck-panel" id="discover-panel-water" role="tabpanel" aria-labelledby="discover-tab-water" data-story-panel hidden><p class="story-deck-kicker">Story 03 · Water</p><h3>Two lakes, one connected system.</h3><p>The district describes Lake Emily feeding Lake Ada Rose before water moves through treatment, storage, pumps, and roughly 60 miles of mains.</p><ol><li><strong>Collect.</strong> Surface water is held in two local reservoirs.</li><li><strong>Treat and store.</strong> The system prepares water and maintains tank storage.</li><li><strong>Move uphill.</strong> Electric pump stations make conservation especially important during outages.</li></ol><a class="button" href="../water/">Follow the water system</a></article>
    <article class="story-deck-panel" id="discover-panel-photos" role="tabpanel" aria-labelledby="discover-tab-photos" data-story-panel hidden><p class="story-deck-kicker">Story 04 · Then and now</p><h3>See the community through its surviving images.</h3><p>Historical photographs, newspaper coverage, and a 1939 railroad brochure preserve different views of the landscape before and during Brooktrails' development.</p><ol><li><strong>Look closely.</strong> Historic images preserve buildings, terrain, and promotion.</li><li><strong>Read in context.</strong> Period documents reflect the language and priorities of their time.</li><li><strong>Compare with today.</strong> The lakes and forest remain central to community identity.</li></ol><a class="button" href="../${docHref('1939 Southern')}">Open the 1939 brochure</a></article>
    <article class="story-deck-panel" id="discover-panel-map" role="tabpanel" aria-labelledby="discover-tab-map" data-story-panel hidden><p class="story-deck-kicker">Story 05 · Orientation</p><h3>Read Brooktrails as a landscape, not a list.</h3><p>Community, water-system, park, and trail maps reveal how homes, reservoirs, roads, and conservation lands relate to one another.</p><ol><li><strong>Community map.</strong> Orient yourself northwest of Willits.</li><li><strong>Water map.</strong> See reservoirs, tanks, and system geography.</li><li><strong>Park map.</strong> Find the greenbelt and recreation network.</li></ol><div class="button-row"><a class="button" href="../${docHref('Hiking Trail Map')}">Open trail map</a><a class="button button-outline-dark" href="../planning/">See the water-system map</a></div></article>
  </div>
</div></div></section>
<section class="section history-band"><div class="shell"><p class="eyebrow eyebrow-light">Continuity</p><h2>Water. Forest. Community. Stewardship.</h2><div class="history-timeline"><div><strong>1939</strong><span>Southern Pacific promotes the Diamond D Ranch area.</span></div><div><strong>1960s</strong><span>Brooktrails development and conservation plans take shape.</span></div><div><strong>1988</strong><span>Ordinance 63 formally establishes Brooktrails Redwood Park.</span></div><div><strong>Today</strong><span>The district continues essential services and stewardship.</span></div></div></div></section>
<section class="section"><div class="shell gallery"><figure><img src="../assets/images/lake-emily.jpg" alt="Lake Emily"><figcaption>Lake Emily</figcaption></figure><figure><img src="../assets/images/lake-ada-rose.jpg" alt="Lake Ada Rose"><figcaption>Lake Ada Rose</figcaption></figure><figure><img src="../assets/images/redwood-park-history.jpg" alt="Historic newspaper articles about Redwood Park"><figcaption>Redwood Park history</figcaption></figure></div></section>`;
await write('history/index.html',page('history/index.html',{title:'Discover Brooktrails',description:'Discover Brooktrails through its history, forest conservation, water system, maps, photographs, and Redwood Park.',active:'history',eyebrow:'Discover Brooktrails',heading:'Follow the stories rooted here.',lede:'From Diamond D Ranch to a community shaped by water and redwoods, choose the thread that draws you in.',body:historyBody}));

const resourcesList = districtDocuments.map(d => `<li data-resource-item data-category="${categoriesFor(d).join(' ')}" data-search="${escapeHtml(`${d.title} ${d.referencedFrom.join(' ')}`.toLowerCase())}"><a href="../${d.file}"><span><strong>${escapeHtml(d.title)}</strong><small>${d.contentType.includes('pdf') ? 'PDF' : 'DOCX'} · ${(d.bytes/1048576).toFixed(1)} MB</small></span><b aria-hidden="true">↓</b></a></li>`).join('');
const categoryButtons = resourceCategories.map((category, index) => {
  const count = districtDocuments.filter(document => categoriesFor(document).includes(category.id)).length;
  return `<button type="button" class="library-shelf${index === 0 ? ' is-active' : ''}" data-resource-category="${category.id}" aria-pressed="${index === 0 ? 'true' : 'false'}"><span>${String(index + 1).padStart(2,'0')}</span><strong>${category.label}</strong><small>${category.hint}</small><b>${count}</b></button>`;
}).join('');
const resourcesBody = `<section class="section section-tint"><div class="shell library-layout" data-resource-library data-default-category="forms"><aside class="library-guide"><p class="eyebrow">Choose a shelf</p><h2>Start with the task, not the filename.</h2><p>Pick a plain-language shelf or search across all ${districtDocuments.length} district files.</p><div class="library-shelves" aria-label="Document categories">${categoryButtons}</div></aside><div class="library-results"><div class="resource-search"><label for="resource-search"><strong>Search the complete district library</strong><span>Try “water”, “rental”, “budget”, or “ordinance”. Search looks across every shelf.</span></label><input id="resource-search" type="search" placeholder="What are you looking for?" data-resource-search></div><div class="library-result-meta"><strong data-resource-heading>Forms & applications</strong><span data-resource-count></span></div><ul class="document-list" data-resource-list>${resourcesList}</ul><p class="empty-state" hidden data-resource-empty>No matching documents found. Try a broader term or another shelf.</p></div></div></section>
<section class="section"><div class="shell two-column"><div><p class="eyebrow">Need context first?</p><h2>The best record is the one you understand.</h2><p>Services explains water, property, and common district tasks before you open a form. District & Board connects civic questions to agendas, financial records, policies, and employment.</p><div class="button-row"><a class="button" href="../services/">Services</a><a class="button button-outline-dark" href="../government/">District & Board</a></div></div><aside class="callout callout-green"><h3>Captured, not guaranteed current</h3><p>This preview preserves the public document set captured on September 10, 2026. Confirm deadlines, fees, availability, and changing policies with the district.</p><a class="button button-light" href="../contact/">District Desk</a></aside></div></section>`;
await write('resources/index.html',page('resources/index.html',{title:'Guided Document Library',description:'Find Brooktrails Township forms and public records by task, category, or search.',active:'services',route:'resources',eyebrow:'Guided document library',heading:'Find one thing. Finish one task.',lede:'The district document collection, reorganized around the reason you came instead of one long municipal file list.',body:resourcesBody}));

const routeRows = routes.map(r=>`<tr><td><code>/${escapeHtml(r.sourceRoute === '/' ? '' : r.sourceRoute)}</code><span>${escapeHtml(r.sourceTitle)}</span></td><td><code>/${escapeHtml(r.destination.replace('/index.html','/').replace('index.html',''))}</code></td><td>${r.disposition === 'retained-and-redesigned' ? 'Redesigned' : r.disposition === 'retained-in-archive-separate-fire-site' ? 'Retained in archive; reserved for separate Fire website' : 'Retained and consolidated'}</td></tr>`).join('');
await write('deliverables/content-migration-review.html', `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Brooktrails content migration review</title><style>body{margin:0;background:#f4f1e8;color:#15241f;font:16px/1.55 system-ui,sans-serif}.wrap{width:min(1100px,calc(100% - 2rem));margin:auto;padding:3rem 0}h1,h2{font-family:Georgia,serif;line-height:1.05}h1{font-size:clamp(2.5rem,6vw,5rem);max-width:12ch}.meta,.note{padding:1rem 1.2rem;background:#e3ede6;border-left:4px solid #1d735f}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:1rem;margin:2rem 0}.stats div{padding:1rem;background:#123b31;color:white}.stats strong{display:block;font-size:2rem;color:#b9fff1}table{width:100%;border-collapse:collapse;background:white}th,td{padding:.8rem;text-align:left;vertical-align:top;border-bottom:1px solid #d6ddd8}th{background:#123b31;color:white}td code{display:block;overflow-wrap:anywhere}td span{font-size:.82rem;color:#52655e}@media(max-width:720px){table,thead,tbody,tr,th,td{display:block}thead{position:absolute;clip:rect(0 0 0 0)}tr{margin-bottom:1rem;border:1px solid #d6ddd8}td:before{display:block;font-size:.7rem;font-weight:800;text-transform:uppercase;color:#1d735f}td:nth-child(1):before{content:'Original route'}td:nth-child(2):before{content:'Preview destination'}td:nth-child(3):before{content:'Disposition'}}</style></head><body><main class="wrap"><p>Reviewer deliverable · September 29, 2026</p><h1>Brooktrails content migration review</h1><p class="meta">This document separates migration accounting from the resident experience. It records how every route captured from the former public sitemap is handled by the staged preview.</p><div class="stats"><div><strong>${routes.length}</strong>captured source routes</div><div><strong>${documents.length}</strong>retained documents</div><div><strong>${routes.filter(r=>r.disposition === 'retained-in-archive-separate-fire-site').length}</strong>Fire routes separated</div><div><strong>noindex</strong>preview policy</div></div><h2>Review boundaries</h2><ul><li>The capture date is September 10, 2026.</li><li>Captured statements are migration source material, not proof that changing facts remain current.</li><li>Fire and Other Emergency Services content is absent from district-facing navigation and preserved only in the source archive pending the separate Fire website.</li><li>Production hosting, DNS, forms, payments, outreach, and district acceptance remain outside this preview.</li></ul><h2>Route disposition</h2><table><thead><tr><th>Original route</th><th>Preview destination</th><th>Disposition</th></tr></thead><tbody>${routeRows}</tbody></table><p class="note">Review outcome should be recorded as accept, revise, hold, or retire. Production migration requires separate scope and authority.</p></main></body></html>`);

const contactBody = `<section class="section district-desk-section"><div class="shell district-desk-layout"><article class="district-desk-primary"><div><span class="contact-icon">${icon('board')}</span><p class="eyebrow">Township office</p><h2>One desk for district questions.</h2><p>For utilities, planning, public records, Board business, fees, deadlines, trail concerns, or a process that may have changed, start here.</p></div><address class="district-desk-channels"><a class="district-desk-channel" href="tel:+17074592494"><small>Call</small><strong>707-459-2494</strong><span>Talk with the district office →</span></a><a class="district-desk-channel" href="mailto:btcsd@btcsd.org"><small>Email</small><strong>btcsd@btcsd.org</strong><span>Write to the district →</span></a><div class="district-desk-channel"><small>Visit or mail</small><strong>24860 Birch Street</strong><span>Willits, CA 95490</span></div><div class="district-desk-channel"><small>Fax</small><strong>707-459-0358</strong><span>District office fax</span></div></address></article><aside class="district-desk-secondary"><span class="contact-icon">${icon('tree')}</span><p class="eyebrow">Golf course</p><h2>Information & tee times</h2><p>The course keeps its own direct line for current tee times, operating details, and conditions.</p><a class="district-desk-course" href="tel:+17074596761"><small>Call the course</small><strong>707-459-6761</strong><span>Tap to call →</span></a><a class="text-link" href="../parks/#parks-panel-golf">See the golf field file →</a></aside></div></section>`;
await write('contact/index.html',page('contact/index.html',{title:'District Desk',description:'Reach the Brooktrails Township district office and golf course from one concise contact hub.',active:null,route:'contact',eyebrow:'District desk',heading:'A person, when a person is the answer.',lede:'The complete district contact directory lives here—kept out of the main trail map, but always one clear step away.',body:contactBody}));

const archiveSections = sourcePages.map(p => `<details id="${sourceId(p.url)}"><summary><span>${escapeHtml(p.title)}</span><small>${escapeHtml(new URL(p.url).pathname || '/')}</small></summary><div><p><a class="text-link" href="${escapeHtml(p.url)}" target="_blank" rel="noopener">Open current source ↗</a></p><pre>${escapeHtml(p.text)}</pre></div></details>`).join('');
const archiveBody = `<section class="section"><div class="shell"><div class="archive-note"><strong>Source snapshot: September 10, 2026</strong><p>This retained text preserves what was publicly rendered across all 30 sitemap pages. Repeated navigation and footer text are intentionally included as source evidence. Current official sources control changing information.</p></div><div class="archive-list">${archiveSections}</div></div></section>`;
await write('archive/index.html',page('archive/index.html',{title:'Retained Source Archive',description:'Text archive of the 30 public btcsd.org sitemap pages captured September 10, 2026.',active:'services',route:'archive',eyebrow:'Retained source archive',heading:'Nothing disappears in the redesign.',lede:'The complete rendered public text remains available for migration review, historical reference, and content parity checks.',body:archiveBody}));

for (const route of routes) {
  const sourcePath = route.sourceRoute === '/' ? '' : route.sourceRoute;
  if (!sourcePath) continue;
  const targetRel = route.destination;
  const aliasRel = `${sourcePath}/index.html`;
  if (aliasRel === targetRel) continue;
  const aliasPrefix = prefixFor(aliasRel);
  const targetHref = `${aliasPrefix}${targetRel.replace('/index.html','/').replace('index.html','')}` || aliasPrefix;
  await write(aliasRel, `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta http-equiv="refresh" content="0;url=${escapeHtml(targetHref)}"><title>Page moved | Brooktrails Township</title><link rel="canonical" href="${escapeHtml(targetHref)}"><link rel="stylesheet" href="${aliasPrefix}styles.css?v=20260930-2"></head><body class="page-redirect"><main class="redirect-page"><h1>This information has moved.</h1><p><a class="button" href="${escapeHtml(targetHref)}">Continue to the updated page</a></p></main></body></html>`);
}

await write('404.html', page('404.html',{title:'Page not found',description:'Find Brooktrails Township services and public information.',active:'home',eyebrow:'404',heading:'That trail ends here.',lede:'The page may have moved during the redesign. Use the links below to get back on course.',body:'<section class="section"><div class="shell button-row"><a class="button" href="index.html">Return home</a><a class="button button-outline-dark" href="resources/">Search documents</a></div></section>'}));

console.log(JSON.stringify({pages:10, redirects:routes.filter(r=>r.sourceRoute !== '/' && `${r.sourceRoute}/index.html` !== r.destination).length + 1, districtDocuments:districtDocuments.length, retainedDocuments:documents.length}, null, 2));
