import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const documents = JSON.parse(await readFile(path.join(root, 'data/documents.json'), 'utf8')).documents;
const routes = JSON.parse(await readFile(path.join(root, 'data/source-routes.json'), 'utf8')).routes;
const sourcePages = JSON.parse(await readFile(path.join(root, 'evidence/source-content-2026-09-10/pages.json'), 'utf8')).pages;

const escapeHtml = value => String(value ?? '')
  .replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;').replaceAll("'", '&#039;');

const nav = [
  ['home', 'Home', 'index.html'],
  ['water', 'Water & Sewer', 'water/'],
  ['fire', 'Fire & Safety', 'fire/'],
  ['parks', 'Parks & Trails', 'parks/'],
  ['planning', 'Planning', 'planning/'],
  ['government', 'Government', 'government/'],
  ['resources', 'Documents', 'resources/'],
  ['contact', 'Contact', 'contact/'],
];

function prefixFor(rel) {
  const depth = rel.split('/').length - 1;
  return '../'.repeat(depth);
}

function icon(name) {
  const paths = {
    water: '<path d="M24 5S10 20 10 31a14 14 0 0 0 28 0C38 20 24 5 24 5Z"/><path d="M17 32c1 5 4 7 8 8"/>',
    fire: '<path d="M29 5c2 9-4 11-4 17-4-3-5-7-4-11-8 7-11 14-8 22 3 8 10 11 17 10 8-1 13-7 13-15 0-9-7-17-14-21 1 6-1 10-5 13 0-5-1-9-3-15Z"/>',
    tree: '<path d="m24 5-9 14h5L11 31h9v12h8V31h9l-9-12h5L24 5Z"/>',
    plan: '<path d="M7 39h34M10 36V15l14-8 14 8v21M17 36V25h14v11"/><path d="M7 18 24 8l17 10"/>',
    board: '<path d="M8 38h32M12 34V18h24v16M18 18v-6h12v6M17 25h2m5 0h2m5 0h2M17 31h2m5 0h2m5 0h2"/>',
    docs: '<path d="M12 5h17l7 7v31H12Z"/><path d="M29 5v8h7M18 22h12M18 28h12M18 34h8"/>',
    phone: '<path d="M14 7 8 10c2 15 15 28 30 30l3-6-9-5-4 4c-6-3-10-7-13-13l4-4-5-9Z"/>',
    alert: '<path d="M24 5 4 41h40L24 5Z"/><path d="M24 17v12m0 6v1"/>',
  };
  return `<svg class="icon" viewBox="0 0 48 48" aria-hidden="true">${paths[name] || paths.docs}</svg>`;
}

function header(active, p) {
  return `<a class="skip-link" href="#main-content">Skip to main content</a>
  <div class="safety-bar">
    <div class="shell safety-grid">
      <a class="safety-call" href="tel:911"><span>Emergency</span><strong>Call 911</strong></a>
      <a href="https://mendoready.org/" target="_blank" rel="noopener"><span>County updates</span><strong>Incidents & Evacuations ↗</strong></a>
      <a href="https://mendoready.org/plan-prepare/" target="_blank" rel="noopener"><span>Be ready</span><strong>Alerts & Evacuation Zones ↗</strong></a>
    </div>
  </div>
  <header class="site-header" data-header>
    <div class="shell masthead">
      <a class="brand" href="${p}index.html" aria-label="Brooktrails Township home">
        <span class="brand-mark" aria-hidden="true"><svg viewBox="0 0 64 64"><path d="M32 3 57 13v19c0 15-9 24-25 29C16 56 7 47 7 32V13L32 3Z"/><path d="m31 13-9 15h5l-8 13h10v10h6V41h10l-8-13h5L31 13Z"/></svg></span>
        <span><strong>Brooktrails Township</strong><small>Community Services District</small></span>
      </a>
      <div class="masthead-actions">
        <a class="utility-link" href="tel:+17074592494">707-459-2494</a>
        <a class="button button-small" href="${p}contact/">Contact the district</a>
      </div>
      <button class="menu-button" type="button" aria-expanded="false" aria-controls="site-nav" data-menu-button><span class="sr-only">Open navigation</span><i></i><i></i><i></i></button>
    </div>
    <nav class="site-nav" id="site-nav" aria-label="Primary navigation" data-nav>
      <div class="shell nav-list">${nav.map(([id, label, href]) => `<a ${id === active ? 'aria-current="page"' : ''} href="${p}${href}">${label}</a>`).join('')}</div>
    </nav>
  </header>`;
}

function footer(p) {
  return `<footer class="site-footer">
    <div class="shell footer-grid">
      <div><strong>Brooktrails Township CSD</strong><p>Essential public services for a forest community northwest of Willits, California.</p></div>
      <div><span class="footer-label">District office</span><p>24860 Birch Street<br>Willits, CA 95490<br><a href="tel:+17074592494">707-459-2494</a></p></div>
      <nav aria-label="Footer navigation"><a href="${p}government/">Board & transparency</a><a href="${p}resources/">Document center</a><a href="${p}contact/">Contact directory</a><a href="https://www.btcsd.org/" target="_blank" rel="noopener">Current district site ↗</a></nav>
    </div>
    <div class="shell footer-base"><span>© <span data-year>2026</span> Brooktrails Township</span><span>Public information, accessible by design.</span></div>
  </footer>`;
}

function page(rel, { title, description, active, eyebrow, heading, lede, heroImage, heroAlt, body, wide = false }) {
  const p = prefixFor(rel);
  const hero = `<section class="page-hero${heroImage ? ' page-hero-image' : ''}">
    <div class="shell ${heroImage ? 'page-hero-grid' : ''}">
      <div class="page-hero-copy"><p class="eyebrow">${eyebrow}</p><h1>${heading}</h1><p>${lede}</p></div>
${heroImage ? `<figure><img src="${p}${heroImage}" alt="${heroAlt}" width="768" height="576"></figure>` : ''}
    </div>
  </section>`;
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="theme-color" content="#06110f"><meta name="description" content="${escapeHtml(description)}"><title>${escapeHtml(title)} | Brooktrails Township</title><link rel="icon" href="${p}assets/favicon.svg"><link rel="stylesheet" href="${p}styles.css?v=20260929-1"><script src="${p}script.js?v=20260929-1" defer></script></head>
<body class="page-${active}"><div class="site-atmosphere" aria-hidden="true"></div>${header(active, p)}<main id="main-content">${hero}<div class="${wide ? '' : 'page-content'}">${body}</div></main>${footer(p)}</body></html>`;
}

async function write(rel, content) {
  const target = path.join(root, rel);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, content);
}

function findDoc(pattern) {
  const rx = new RegExp(pattern, 'i');
  return documents.find(d => rx.test(d.title));
}

function docHref(pattern, fallback = 'resources/') {
  const document = findDoc(pattern);
  return document ? document.file : fallback;
}

function docLink(pattern, label) {
  const d = findDoc(pattern);
  return d ? `<a class="resource-link" href="${prefixFor('x/index.html')}${d.file}">${label || escapeHtml(d.title)} <span aria-hidden="true">↓</span></a>` : '';
}

const homeBody = `<section class="home-hero">
  <div class="shell home-hero-grid"><div class="home-hero-copy"><p class="eyebrow eyebrow-light">Your field guide to Brooktrails</p><h1>Between water,<br><em>fire & redwoods.</em></h1><p>One forest community. One clear path to the services, decisions, and places that shape life here.</p><div class="button-row"><a class="button button-light" href="water/">Explore resident services</a><a class="button button-ghost" href="resources/">Open the document trail</a></div><div class="hero-signal" aria-label="Brooktrails service overview"><span><b>6</b> service paths</span><span><b>51</b> public records</span><span><b>24/7</b> emergency access</span></div></div><figure class="home-hero-image"><img src="assets/images/lake-emily.jpg" alt="Lake Emily surrounded by forest in Brooktrails" width="768" height="576"><figcaption>Lake Emily, part of the Brooktrails water supply</figcaption></figure></div>
  <div class="shell quick-actions" aria-label="Resident quick actions"><a href="https://www.btcsd.org/" target="_blank" rel="noopener">Pay water bill <span>↗</span></a><a href="government/">Board meeting materials <span>→</span></a><a href="planning/">Plan a building project <span>→</span></a><a href="contact/">Report an issue <span>→</span></a></div>
</section>
<section class="section"><div class="shell"><div class="section-intro"><div><p class="eyebrow">Choose your trail</p><h2>What brings you here?</h2></div><p>Every path leads to a useful next step, with the right contact, record, or public service close at hand.</p></div><div class="service-grid">
  <a class="service-card" href="water/"><span class="service-icon">${icon('water')}</span><h3>Manage water & sewer</h3><p>Pay a bill, review water quality, conserve water, or find utility forms.</p><span class="card-arrow">Explore utilities →</span></a>
  <a class="service-card service-card-fire" href="fire/"><span class="service-icon">${icon('fire')}</span><h3>Prepare for emergencies</h3><p>Reach fire contacts, wildfire resources, evacuation guidance, and burn authorities.</p><span class="card-arrow">Fire & safety →</span></a>
  <a class="service-card" href="parks/"><span class="service-icon">${icon('tree')}</span><h3>Enjoy parks & trails</h3><p>Explore Redwood Park, maps, rental resources, and trail stewardship.</p><span class="card-arrow">Parks & trails →</span></a>
  <a class="service-card" href="planning/"><span class="service-icon">${icon('plan')}</span><h3>Plan a project</h3><p>Understand development review before grading, tree cutting, or construction.</p><span class="card-arrow">Planning & design →</span></a>
  <a class="service-card" href="government/"><span class="service-icon">${icon('board')}</span><h3>Follow your district</h3><p>Meet the Board, find meetings, review budgets, policies, audits, and public records.</p><span class="card-arrow">Local government →</span></a>
  <a class="service-card" href="resources/"><span class="service-icon">${icon('docs')}</span><h3>Find forms & documents</h3><p>Search the retained public library of reports, ordinances, applications, and plans.</p><span class="card-arrow">Document center →</span></a>
</div></div></section>
<section class="section landscape-band"><div class="shell landscape-grid"><div><p class="eyebrow eyebrow-light">The landscape is the infrastructure</p><h2>Everything starts with this place.</h2><p>Brooktrails sits northwest of Willits in northern Mendocino County. The district helps protect essential infrastructure, public safety, local recreation, and roughly 2,500 acres dedicated as conservation land in Brooktrails Redwood Park.</p><a class="text-link text-link-light" href="history/">Step into Brooktrails history →</a></div><div class="stat-stack"><div><strong>2,500</strong><span>approximate acres dedicated to Redwood Park</span></div><div><strong>60</strong><span>miles of water mains described by the district</span></div><div><strong>911</strong><span>for any life or property emergency</span></div></div></div></section>
<section class="section"><div class="shell split-feature"><div><p class="eyebrow">See behind the decisions</p><h2>Local government, without the fog.</h2><p>Find the next meeting, the people responsible, and the public records behind decisions without digging through a conventional municipal maze.</p><div class="button-row"><a class="button" href="government/">Meet the district</a><a class="button button-outline-dark" href="resources/">Follow the document trail</a></div></div><figure><img src="assets/images/board-of-directors-2025.jpg" alt="Brooktrails Township Board of Directors pictured in 2025" width="1170" height="724"><figcaption>Brooktrails Township Board of Directors, source image dated 2025</figcaption></figure></div></section>`;

await write('index.html', `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="theme-color" content="#06110f"><meta name="description" content="Brooktrails Township Community Services District information for water, sewer, fire safety, parks, planning, meetings, and public documents."><title>Brooktrails Township Community Services District</title><link rel="icon" href="assets/favicon.svg"><link rel="stylesheet" href="styles.css?v=20260929-1"><script src="script.js?v=20260929-1" defer></script></head><body class="page-home"><div class="site-atmosphere" aria-hidden="true"></div>${header('home','')}<main id="main-content">${homeBody}</main>${footer('')}</body></html>`);

const waterBody = `<section class="section"><div class="shell"><div class="metric-row"><div><strong>9,000</strong><span>gallon monthly customer use limit</span></div><div><strong>1.2 MGD</strong><span>water treatment design capacity</span></div><div><strong>60 miles</strong><span>of water mains</span></div><div><strong>18</strong><span>pump stations</span></div></div></div></section>
<section class="section section-tint"><div class="shell"><div class="section-intro"><div><p class="eyebrow">Resident utility desk</p><h2>Common water & sewer needs</h2></div><p>Use the district's published resources, or call the office before relying on connection availability or a time-sensitive policy.</p></div><div class="action-grid"><a href="https://www.btcsd.org/" target="_blank" rel="noopener"><strong>Pay your bill</strong><span>Open current district payment access ↗</span></a>${['Consumer Confidence','Rates and Fees','Utilities Code','Payment Plan','Water Shut-Off','sewer lateral'].map((q,i)=>{const d=findDoc(q);return d?`<a href="../${d.file}"><strong>${escapeHtml(d.title)}</strong><span>Download ${d.contentType.includes('pdf')?'PDF':'file'} ↓</span></a>`:''}).join('')}</div></div></section>
<section class="section"><div class="shell story-grid"><div><p class="eyebrow">Brooktrails water system</p><h2>Surface water, stored close to home.</h2><p>The district describes two reservoirs totaling about 400 acre-feet on Willits Creek and a tributary. Lake Emily feeds Lake Ada Rose before water moves to the treatment plant.</p><p>The public system description includes a 1.2 million gallon-per-day treatment plant, 60 miles of mains, 24 water tanks, and 18 pump stations. Annual Consumer Confidence Reports provide testing and water-quality results.</p><a class="text-link" href="../${docHref('Consumer Confidence')}">Read the 2025 Consumer Confidence Report →</a></div><div class="image-pair"><figure><img src="../assets/images/lake-emily.jpg" alt="Lake Emily reservoir"><figcaption>Lake Emily</figcaption></figure><figure><img src="../assets/images/lake-ada-rose.jpg" alt="Lake Ada Rose reservoir"><figcaption>Lake Ada Rose</figcaption></figure></div></div></section>
<section class="section forest-panel"><div class="shell two-column"><div><p class="eyebrow eyebrow-light">Conservation</p><h2>Save water when the power goes out.</h2><p>The system relies on electric pumps to fill storage tanks. During outages, using less water helps the community maintain service while generators support the system.</p><p>Every water customer is subject to a 9,000 gallon monthly use limit. The district's conservation resources cover meter reading, indoor and outdoor efficiency, rainwater, graywater, pools, irrigation, and professional resources.</p></div><aside class="callout"><h3>Water service and new connections</h3><p>Published source pages contain different point-in-time connection counts. Availability changes. Contact the district office before planning a purchase or construction project.</p><a class="button button-light" href="../contact/">Contact utilities</a></aside></div></section>
<section class="section"><div class="shell two-column"><div><p class="eyebrow">Wastewater</p><h2>Sewer service & lateral inspections</h2><p>The district provides wastewater collection for most of Brooktrails, while Spring Creek, Sylvandale, and some higher-elevation Brooktrails properties are not served by the collection system. Wastewater is treated at the City of Willits Wastewater Treatment Plant.</p><p>Sewer lateral inspections are required when an owner or tenant moves into a residence that has not been inspected within the last five years. Check with the district office for the address's last inspection date.</p></div><div class="resource-panel"><h3>Utility documents</h3>${['sewer lateral','Ordinance 121','no wet wipe','water meter construction','Rates and Fees'].map(q=>{const d=findDoc(q);return d?`<a href="../${d.file}">${escapeHtml(d.title)} <span>↓</span></a>`:''}).join('')}</div></div></section>`;
await write('water/index.html', page('water/index.html',{title:'Water & Sewer',description:'Brooktrails water, sewer, billing, conservation, water quality, and utility forms.',active:'water',eyebrow:'Water & sewer',heading:'Reliable service starts with clear information.',lede:'Pay a bill, understand the water system, conserve supplies, and find the forms and reports that support your property.',heroImage:'assets/images/lake-emily.jpg',heroAlt:'Lake Emily, a Brooktrails water source',body:waterBody}));

const fireBody = `<section class="section"><div class="shell emergency-cards"><a class="emergency-card" href="tel:911">${icon('alert')}<span>Life or property emergency</span><strong>Call 911</strong></a><a class="emergency-card emergency-card-dark" href="https://mendoready.org/" target="_blank" rel="noopener">${icon('alert')}<span>Official county information</span><strong>Incidents & evacuations ↗</strong></a><a class="emergency-card emergency-card-gold" href="https://mendoready.org/plan-prepare/" target="_blank" rel="noopener">${icon('tree')}<span>Prepare before an alert</span><strong>Know your zone ↗</strong></a></div></section>
<section class="section section-tint"><div class="shell fire-intro"><div class="fire-badge"><img src="../assets/images/brooktrails-fire-badge.png" alt="Brooktrails Fire Department badge" width="223" height="227"></div><div><p class="eyebrow">Neighbors serving neighbors</p><h2>All-risk response for Brooktrails, Spring Creek & Sylvandale.</h2><p>The department serves these forest communities and its surrounding sphere of influence with fire response, basic life support, rescue, prevention, and mutual aid across Mendocino County.</p><div class="button-row"><a class="button" href="mailto:fireprev@btcsd.org?subject=Volunteer%20firefighter%20interest">Ask about volunteering</a><a class="button button-outline-dark" href="tel:+17074594441">Call 707-459-4441</a></div></div></div></section>
<section class="section"><div class="shell"><div class="section-intro"><div><p class="eyebrow">Prepare now</p><h2>Wildfire readiness is a household practice.</h2></div><p>Use more than one source for alerts, know your evacuation zone, maintain defensible space, and leave early if conditions feel unsafe.</p></div><div class="service-grid three"><a class="service-card" href="https://mendoready.org/plan-prepare/" target="_blank" rel="noopener"><h3>Sign up for alerts</h3><p>Register for official Mendocino County emergency notifications.</p><span class="card-arrow">MendoReady ↗</span></a><a class="service-card" href="https://mendoready.org/" target="_blank" rel="noopener"><h3>Know your zone</h3><p>Save the zones for home, work, school, and family locations.</p><span class="card-arrow">Find your zone ↗</span></a><a class="service-card" href="https://www.readyforwildfire.org/prepare-for-wildfire/defensible-space/" target="_blank" rel="noopener"><h3>Create defensible space</h3><p>Clear combustibles and maintain vegetation around structures.</p><span class="card-arrow">CAL FIRE guidance ↗</span></a></div></div></section>
<section class="section fire-band"><div class="shell two-column"><div><p class="eyebrow eyebrow-light">Burn permits</p><h2>Check both fire safety and air quality before burning.</h2><p>Brooktrails does not determine burn season. CAL FIRE and the Mendocino County Air Quality Management District control the applicable burn status and requirements. Always recheck on the day you plan to burn.</p></div><div class="resource-panel resource-panel-light"><a href="https://burnpermit.fire.ca.gov/current-burn-status" target="_blank" rel="noopener">CAL FIRE burn status & permit access ↗</a><a href="https://mcaqmd.org/burn-information/" target="_blank" rel="noopener">Mendocino AQMD burn information ↗</a><a href="tel:+17074634391">Daily AQMD burn line: 707-463-4391</a><a href="tel:+17074597414">CAL FIRE Willits: 707-459-7414</a></div></div></section>
<section class="section"><div class="shell two-column"><div><p class="eyebrow">Station contact</p><h2>Brooktrails Fire Department</h2><address class="contact-card"><span>24860 Birch Street<br>Willits, CA 95490-9475</span><a href="tel:+17074594441">707-459-4441</a><a href="mailto:fireprev@btcsd.org">fireprev@btcsd.org</a><span>Fax: 707-459-1517</span></address></div><figure class="feature-photo"><img src="../assets/station-exterior.jpg" alt="Brooktrails Fire Department station at Birch Street"><figcaption>Brooktrails Fire Department station</figcaption></figure></div></section>`;
await write('fire/index.html',page('fire/index.html',{title:'Fire & Emergency Safety',description:'Brooktrails Fire Department contacts, emergency resources, wildfire preparation, burn information, and volunteering.',active:'fire',eyebrow:'Fire & emergency safety',heading:'Ready for the calls a forest community faces.',lede:'Emergency action comes first, followed by trusted preparedness resources, volunteer service, and direct station contact.',heroImage:'assets/station-exterior.jpg',heroAlt:'Brooktrails Fire Department station on Birch Street',body:fireBody}));

const parksBody = `<section class="section"><div class="shell story-grid"><div><p class="eyebrow">Brooktrails Redwood Park</p><h2>Conservation land woven through the community.</h2><p>Approximately 2,500 acres were dedicated by the original developer for conservation and recreation. The district continued that intent through Brooktrails Redwood Park, including active-use, neighborhood-use, and passive-use areas.</p><p>Ordinance 63 formally established the park in 1988. Ordinance 68 adopted a master plan later that year. A Greenbelt Stewardship Plan was adopted by Resolution 2013-14 after years of community committee work.</p><div class="button-row"><a class="button" href="../${docHref('Hiking Trail Map')}">Download trail map</a><a class="button button-outline-dark" href="../${docHref('Greenbelt Stewardship')}">Stewardship plan</a></div></div><figure class="feature-photo"><img src="../assets/images/redwood-park-history.jpg" alt="Historical newspaper coverage of Brooktrails conservation plans"><figcaption>Historical coverage of the Brooktrails conservation vision</figcaption></figure></div></section>
<section class="section section-tint"><div class="shell"><div class="section-intro"><div><p class="eyebrow">Go outside</p><h2>Parks, trails & gathering places</h2></div><p>Find the current district resources for recreation areas, rentals, trail locations, and maintenance requests.</p></div><div class="action-grid">${['Trail Maintenance','Community Center Rental','Ohl Redwood Grove','Hiking Trail Map','Ordinance 63','Committee Charter'].map(q=>{const d=findDoc(q);return d?`<a href="../${d.file}"><strong>${escapeHtml(d.title)}</strong><span>Download ↓</span></a>`:''}).join('')}<a href="https://www.google.com/maps/search/?api=1&query=Brooktrails+Redwood+Park+Willits+CA" target="_blank" rel="noopener"><strong>Trail locations</strong><span>Open map ↗</span></a></div></div></section>
<section class="section"><div class="shell two-column"><div><p class="eyebrow">Community stewardship</p><h2>Recreation, Greenbelt & Conservation Committee</h2><p>The committee's published schedule is the third Thursday of every other month at 7:00 p.m. in the Brooktrails Community Center. Confirm the next meeting with the district before attending.</p><p>Willits Area Cyclists partners with the district as trail stewards through organized maintenance and trail work.</p></div><aside class="callout callout-green"><h3>See something on a trail?</h3><p>Use the district's retained trail maintenance request form to share the location and issue.</p><a class="button button-light" href="../${docHref('Trail Maintenance')}">Trail request form</a></aside></div></section>`;
await write('parks/index.html',page('parks/index.html',{title:'Parks & Trails',description:'Brooktrails Redwood Park, conservation lands, trails, maps, rentals, and stewardship resources.',active:'parks',eyebrow:'Parks, trails & greenbelt',heading:'Keep close to the redwoods.',lede:'Explore the conservation legacy, public-use areas, trails, rental resources, and community stewardship of Brooktrails Redwood Park.',heroImage:'assets/images/diamond-d-ranch-history.jpg',heroAlt:'Historic Diamond D Ranch headquarters in Brooktrails',body:parksBody}));

const planningBody = `<section class="section"><div class="shell"><div class="process"><div><span>1</span><h3>Start with the district</h3><p>Before grading, tree cutting, or construction, contact Township staff and review the Brooktrails standards.</p></div><div><span>2</span><h3>Prepare your plan</h3><p>Use the development standards, application packet, and construction water-meter materials.</p></div><div><span>3</span><h3>Coordinate county review</h3><p>Projects also require the applicable Mendocino County Planning & Building Services approval.</p></div></div></div></section>
<section class="section section-tint"><div class="shell two-column"><div><p class="eyebrow">Development review</p><h2>Plan first, then build.</h2><p>Brooktrails properties are subject to development standards and a review process consistent with the Brooktrails Specific Plan adopted by Mendocino County. Township staff, and the District Architect when required, evaluate proposed plans.</p><p>The district and county jointly administer the Brooktrails Specific Plan and its 2004 amendments.</p><a class="button" href="../contact/">Contact the Township office</a></div><div class="resource-panel"><h3>Planning packet</h3>${['Development Standards','Design Review Application','Water Meter Construction','Chapter 20.232','Ordinance 121','Ordinance 112','2004 Specific Plan'].map(q=>{const d=findDoc(q);return d?`<a href="../${d.file}">${escapeHtml(d.title)} <span>↓</span></a>`:''}).join('')}</div></div></section>
<section class="section"><div class="shell story-grid"><div><p class="eyebrow">Long-range planning</p><h2>Growth, water & a second access road.</h2><p>The district describes its planning authority as a response to water-right and growth questions raised in the late 1980s. A second access road has remained an important planning element, with alternative-route work presented in 2009 and funding limitations reported in 2013.</p><p>Historical planning records remain available in the document center so current decisions can be read in context.</p><a class="text-link" href="../resources/">Browse planning records →</a></div><figure class="feature-photo map-photo"><img src="../assets/images/water-system-map.jpg" alt="Map showing Brooktrails water system and tank locations"><figcaption>Water system and tank locations</figcaption></figure></div></section>`;
await write('planning/index.html',page('planning/index.html',{title:'Planning & Development',description:'Brooktrails planning, building and development review process, standards, applications, and historical planning context.',active:'planning',eyebrow:'Planning & development',heading:'A clearer path from idea to approval.',lede:'Understand the Township and County review steps, gather the right documents, and contact staff before site work begins.',body:planningBody}));

const governmentBody = `<section class="section"><div class="shell split-feature"><div><p class="eyebrow">Board of Directors</p><h2>Five residents, one public trust.</h2><p>The Board sets district policy and appoints the General Manager, General Counsel, and Auditor. Published source information lists Tina Tyler-O'Shea as President and Rick Williams as Vice-President, with Ed Horrick, Susan Mahoney, and Mary Ziady serving as directors.</p><p>Terms published by the district run through December 2026 or December 2028. Confirm current membership and meeting materials with the district office.</p><a class="button" href="../${docHref('Agenda for Most Recent')}">Most recent agenda</a></div><figure><img src="../assets/images/board-of-directors-2025.jpg" alt="Five members of the Brooktrails Township Board of Directors"><figcaption>Board of Directors, source image dated 2025</figcaption></figure></div></section>
<section class="section section-tint"><div class="shell"><div class="section-intro"><div><p class="eyebrow">Administration</p><h2>People, policy & public records</h2></div><p>The General Manager is responsible for Township operations under Board policy. The public source names Tamara Alaniz as General Manager, Christopher J. Neary as General Counsel, and JJACPA as Auditor.</p></div><div class="service-grid three"><article class="service-card static"><h3>Financials</h3><p>Budget, rates and fees, annual audit, compensation, and the 2019 Municipal Service Review.</p><a class="card-arrow" href="../resources/">Financial documents →</a></article><article class="service-card static"><h3>Policies & ordinances</h3><p>Board-adopted policy manual, utilities code, ordinances, resolutions, and development rules.</p><a class="card-arrow" href="../resources/">Policy library →</a></article><article class="service-card static"><h3>Public systems</h3><p>The SB 272 Enterprise System Catalog describes systems containing information collected about the public.</p><a class="card-arrow" href="../${docHref('Enterprise Systems')}">Enterprise catalog ↓</a></article></div></div></section>
<section class="section"><div class="shell two-column"><div><p class="eyebrow">Employment</p><h2>Serve the community.</h2><p>The captured district site listed Firefighter/Engineer and Water/Sewer Utility Operator positions. Employment status, pay, qualifications, and deadlines can change. Confirm openings with the district before applying.</p><a class="button" href="../${docHref('EMPLOYMENT APPLICATION')}">Employment application</a></div><div class="resource-panel"><h3>Featured public records</h3>${['Financial Plan','annual audit','Rates and Fees','Policy Manual','Organizational','Municipal Service'].map(q=>{const d=findDoc(q);return d?`<a href="../${d.file}">${escapeHtml(d.title)} <span>↓</span></a>`:''}).join('')}</div></div></section>`;
await write('government/index.html',page('government/index.html',{title:'Board & District Government',description:'Brooktrails Board, administration, meetings, public records, financials, policies, and employment information.',active:'government',eyebrow:'Board & district government',heading:'Local decisions, made visible.',lede:'Meet the Board, follow district business, and reach the budgets, policies, audits, and records behind public service.',body:governmentBody}));

const historyBody = `<section class="section"><div class="shell story-grid"><div><p class="eyebrow">The essence of Brooktrails</p><h2>A community planned around forest conservation.</h2><p>Brooktrails grew from the former Diamond D Ranch northwest of Willits. In the late 1960s, development plans paired homes and infrastructure with a large conservation dedication that became Brooktrails Redwood Park.</p><p>The community's public history spans resort-era promotion, formation of local improvement districts, transition to a Community Services District, water and wastewater development, fire protection, recreation, and decades of planning around life in a forest setting.</p><p>Historical claims and interpretations can be explored in full through the retained source archive and original documents.</p><div class="button-row"><a class="button" href="../archive/">Read retained source text</a><a class="button button-outline-dark" href="../${docHref('1939 Southern')}">1939 railroad brochure</a></div></div><figure class="feature-photo"><img src="../assets/images/diamond-d-ranch-history.jpg" alt="Historic Diamond D Ranch headquarters"><figcaption>Diamond D Ranch headquarters, historical source image</figcaption></figure></div></section>
<section class="section history-band"><div class="shell"><p class="eyebrow eyebrow-light">Continuity</p><h2>Water. Fire. Forest. Community.</h2><div class="history-timeline"><div><strong>1939</strong><span>Southern Pacific promotes the Diamond D Ranch area.</span></div><div><strong>1960s</strong><span>Brooktrails development and conservation plans take shape.</span></div><div><strong>1988</strong><span>Ordinance 63 formally establishes Brooktrails Redwood Park.</span></div><div><strong>Today</strong><span>The district continues essential services and stewardship.</span></div></div></div></section>
<section class="section"><div class="shell gallery"><figure><img src="../assets/images/lake-emily.jpg" alt="Lake Emily"><figcaption>Lake Emily</figcaption></figure><figure><img src="../assets/images/wildfire-history.jpg" alt="Historical wildfire material"><figcaption>Wildfire history</figcaption></figure><figure><img src="../assets/images/redwood-park-history.jpg" alt="Historic newspaper articles about Redwood Park"><figcaption>Redwood Park history</figcaption></figure></div></section>`;
await write('history/index.html',page('history/index.html',{title:'Brooktrails History',description:'Brooktrails history, forest conservation, community development, water, fire protection, and Redwood Park.',active:'home',eyebrow:'About Brooktrails',heading:'History held in the landscape.',lede:'From Diamond D Ranch to a community services district, Brooktrails has been shaped by water, fire, forest, and local stewardship.',body:historyBody}));

const resourcesList = documents.map(d => `<li data-resource-item data-search="${escapeHtml(`${d.title} ${d.referencedFrom.join(' ')}`.toLowerCase())}"><a href="../${d.file}"><span><strong>${escapeHtml(d.title)}</strong><small>${d.contentType.includes('pdf') ? 'PDF' : 'DOCX'} · ${(d.bytes/1048576).toFixed(1)} MB</small></span><b aria-hidden="true">↓</b></a></li>`).join('');
const routeRows = routes.map(r=>`<tr><td><code>/${escapeHtml(r.sourceRoute === '/' ? '' : r.sourceRoute)}</code><span>${escapeHtml(r.sourceTitle)}</span></td><td>${escapeHtml(r.destination.replace('/index.html','/'))}</td><td>${r.disposition === 'retained-and-redesigned' ? 'Redesigned' : 'Retained & consolidated'}</td></tr>`).join('');
const resourcesBody = `<section class="section"><div class="shell"><div class="resource-search"><label for="resource-search"><strong>Search 51 retained documents</strong><span>Budgets, policies, ordinances, plans, applications, maps, reports, and historical records.</span></label><input id="resource-search" type="search" placeholder="Try “water”, “ordinance”, or “budget”" data-resource-search></div><ul class="document-list" data-resource-list>${resourcesList}</ul><p class="empty-state" hidden data-resource-empty>No matching documents found. Try a broader term.</p></div></section>
<section class="section section-tint"><div class="shell"><div class="section-intro"><div><p class="eyebrow">Content migration</p><h2>Every public route has a destination.</h2></div><p>The old site's 30 sitemap pages are retained, redesigned, or consolidated into this clearer information architecture.</p></div><div class="table-wrap"><table><thead><tr><th>Original route</th><th>New destination</th><th>Disposition</th></tr></thead><tbody>${routeRows}</tbody></table></div><a class="button" href="../archive/">Open full retained text archive</a></div></section>`;
await write('resources/index.html',page('resources/index.html',{title:'Document Center',description:'Search Brooktrails Township public documents, forms, reports, ordinances, plans, maps, and retained source records.',active:'resources',eyebrow:'Document center',heading:'Public records, without the scavenger hunt.',lede:'Search the complete downloadable document set captured from the district website on September 10, 2026.',body:resourcesBody}));

const contactBody = `<section class="section"><div class="shell contact-directory"><article><span class="contact-icon">${icon('board')}</span><p class="eyebrow">District office</p><h2>Brooktrails Township CSD</h2><address><span>24860 Birch Street<br>Willits, CA 95490</span><a href="tel:+17074592494">707-459-2494</a><a href="mailto:btcsd@btcsd.org">btcsd@btcsd.org</a><span>Fax: 707-459-0358</span></address></article><article class="contact-fire"><span class="contact-icon">${icon('fire')}</span><p class="eyebrow">Fire department</p><h2>Non-emergency station</h2><address><span>24860 Birch Street<br>Willits, CA 95490-9475</span><a href="tel:+17074594441">707-459-4441</a><a href="mailto:fireprev@btcsd.org">fireprev@btcsd.org</a><span>Fax: 707-459-1517</span></address><a class="button button-light" href="tel:911">Emergency: Call 911</a></article><article><span class="contact-icon">${icon('tree')}</span><p class="eyebrow">Golf course</p><h2>Information & tee times</h2><address><a href="tel:+17074596761">707-459-6761</a></address></article></div></section>
<section class="section section-tint"><div class="shell"><div class="section-intro"><div><p class="eyebrow">Other agencies</p><h2>Find the right public service.</h2></div><p>Some issues in Brooktrails are handled by Mendocino County or the State of California rather than the district.</p></div><div class="contact-list"><div><strong>Road-related issues</strong><span>Mendocino County Department of Transportation</span><a href="tel:+17074634363">707-463-4363</a></div><div><strong>Criminal complaints / illegal cannabis</strong><span>Mendocino County Sheriff, Willits substation</span><a href="tel:+17074597833">707-459-7833</a></div><div><strong>Code enforcement / private-property vehicles</strong><span>Mendocino County Planning & Building</span><a href="tel:+17072346650">707-234-6650</a></div><div><strong>Illegal parking / right-of-way vehicles</strong><span>California Highway Patrol</span><a href="tel:+17074634717">707-463-4717</a></div><div><strong>Animals, dead or alive</strong><span>Mendocino County Animal Control</span><a href="tel:+17074634427">707-463-4427</a></div></div></div></section>`;
await write('contact/index.html',page('contact/index.html',{title:'Contact',description:'Contact Brooktrails Township, Brooktrails Fire Department, the golf course, and other responsible public agencies.',active:'contact',eyebrow:'Contact directory',heading:'Reach the right office, faster.',lede:'Direct district, fire, recreation, and partner-agency contacts in one place.',body:contactBody}));

const archiveSections = sourcePages.map(p => `<details><summary><span>${escapeHtml(p.title)}</span><small>${escapeHtml(new URL(p.url).pathname || '/')}</small></summary><div><p><a class="text-link" href="${escapeHtml(p.url)}" target="_blank" rel="noopener">Open current source ↗</a></p><pre>${escapeHtml(p.text)}</pre></div></details>`).join('');
const archiveBody = `<section class="section"><div class="shell"><div class="archive-note"><strong>Source snapshot: September 10, 2026</strong><p>This retained text preserves what was publicly rendered across all 30 sitemap pages. Repeated navigation and footer text are intentionally included as source evidence. Current official sources control changing information.</p></div><div class="archive-list">${archiveSections}</div></div></section>`;
await write('archive/index.html',page('archive/index.html',{title:'Retained Source Archive',description:'Text archive of the 30 public btcsd.org sitemap pages captured September 10, 2026.',active:'resources',eyebrow:'Retained source archive',heading:'Nothing disappears in the redesign.',lede:'The complete rendered public text remains available for migration review, historical reference, and content parity checks.',body:archiveBody}));

for (const route of routes) {
  const sourcePath = route.sourceRoute === '/' ? '' : route.sourceRoute;
  if (!sourcePath) continue;
  const targetRel = route.destination;
  const aliasRel = `${sourcePath}/index.html`;
  if (aliasRel === targetRel) continue;
  const aliasPrefix = prefixFor(aliasRel);
  const targetHref = `${aliasPrefix}${targetRel.replace('/index.html','/').replace('index.html','')}` || aliasPrefix;
  await write(aliasRel, `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta http-equiv="refresh" content="0;url=${escapeHtml(targetHref)}"><title>Page moved | Brooktrails Township</title><link rel="canonical" href="${escapeHtml(targetHref)}"><link rel="stylesheet" href="${aliasPrefix}styles.css?v=20260929-1"></head><body class="page-redirect"><main class="redirect-page"><h1>This information has moved.</h1><p><a class="button" href="${escapeHtml(targetHref)}">Continue to the updated page</a></p></main></body></html>`);
}

await write('404.html', page('404.html',{title:'Page not found',description:'Find Brooktrails Township services and public information.',active:'home',eyebrow:'404',heading:'That trail ends here.',lede:'The page may have moved during the redesign. Use the links below to get back on course.',body:'<section class="section"><div class="shell button-row"><a class="button" href="index.html">Return home</a><a class="button button-outline-dark" href="resources/">Search documents</a></div></section>'}));

console.log(JSON.stringify({pages:10, redirects:routes.filter(r=>r.sourceRoute !== '/' && `${r.sourceRoute}/index.html` !== r.destination).length, documents:documents.length}, null, 2));
